const dagelijkseFeitjes = [
    // --- JANUARI ---
    { d: "1 januari", s: "Als januari begint met een goede sfeer, brengt de rest van het jaar vaak mooi weer." },
    { d: "2 januari", s: "Januari zonder regen is voor de boerenstand een zegen." },
    { d: "3 januari", s: "Geeft januari een sneeuwtapijt, dan zijn we gauw de winter kwijt." },
    { d: "4 januari", s: "Als de kat in januari in de zon ligt, ligt ze in februari achter de kachel." },
    { d: "5 januari", s: "Als de dagen lengen, begint de winter te strengen." },
    { d: "6 januari", s: "Draagt januari een sneeuwwit kleed, wordt de zomer zeer heet." },
    { d: "7 januari", s: "Knapt januari niet van kou, dan zit men in de oogst in de rouw." },
    { d: "8 januari", s: "Is januari guur en koud, dan wordt de boer een rijke man genoemd." },
    { d: "9 januari", s: "Heeft januari felle kou, dan volgt een zomer waar men op bouwen kan." },
    { d: "10 januari", s: "Als het in januari mistig is, dan is een natte lente gewis." },
    { d: "11 januari", s: "Brengt januari felle koude, de winter zal niet lang meer houden." },
    { d: "12 januari", s: "Als januari de vorst niet brengt, de zomer vaak met regen mengt." },
    { d: "13 januari", s: "Sint-Hilarius (13 jan) met veel kou, brengt de winter in het nauw." },
    { d: "14 januari", s: "Als de winter in januari niet vriezen wil, dan vriest het in maart of april." },
    { d: "15 januari", s: "Januari koud en nat, vult de schuur en ook het vat." },
    { d: "16 januari", s: "Sint-Anthonius (17 jan) klaar en helder, vult het vat en ook de kelder." },
    { d: "17 januari", s: "Als het vriest op Sint-Sebastiaan (20 jan), dan zal de winter nog lang aanhouden." },
    { d: "18 januari", s: "Sint-Agnes (21 jan) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "19 januari", s: "Is januari zacht en nat, dan krijgt de winter een late spat." },
    { d: "20 januari", s: "Vincentius (22 jan) zonneschijn, geeft veel koren en goede wijn." },
    { d: "21 januari", s: "Als het op Sint-Paulus (25 jan) helder is, is het jaar van granen gewis." },
    { d: "22 januari", s: "Januari zacht, winter met macht." },
    { d: "23 januari", s: "Als januari de muggen zwermen, moet men in maart de schapen beschermen." },
    { d: "24 januari", s: "Is januari warm en nat, dan raakt de boer zijn oogst duchtig zat." },
    { d: "25 januari", s: "Klaar weer op Sint-Paulusnacht, brengt het jaar een goede oogst met macht." },
    { d: "26 januari", s: "Veel sneeuw in de wintermaand, veel hooi op de weide." },
    { d: "27 januari", s: "Als januari geen vorst wil dragen, komt die in de lentedagen." },
    { d: "28 januari", s: "Heeft januari felle zon, dan droogt de boer zijn waterbron." },
    { d: "29 januari", s: "Als het in de wintermaand hard waait, wordt het koren goed gezaaid." },
    { d: "30 januari", s: "Januari koud en guur, maakt het spek op de zolder duur." },
    { d: "31 januari", s: "Als de eerste maand ons vriezen laat, de zomer vroeg in bloei staat." },
    // --- FEBRUARI ---
    { d: "1 februari", s: "In de sprokkelmaand koud en guur, is de winter van korte duur." },
    { d: "2 februari", s: "Maria Lichtmis (2 feb) helder en klaar, maakt de boer tot bedelaar." },
    { d: "3 februari", s: "Lichtmis in de klaver, Pasen in de sneeuw." },
    { d: "4 februari", s: "Als het op Lichtmis helder is, krijgt de winter een staart gewis." },
    { d: "5 februari", s: "Februari regen, is de landman zijn zegen." },
    { d: "6 februari", s: "Februari zacht en stil, dan komt de noordenwind in april." },
    { d: "7 februari", s: "Februari zonder storm, in april is hij in vorm." },
    { d: "8 februari", s: "Gaan de mieren al aan 't sparen, zullen kou en vorst gewis niet sparen." },
    { d: "9 februari", s: "Geeft de sprokkelmaand de winter niet, is hij voor Pasen in het verschiet." },
    { d: "10 februari", s: "Geeft februari muggendans, voor maart is er een slechte kans." },
    { d: "11 februari", s: "Groeit in februari het gras, met Pasen een dikke jas." },
    { d: "12 februari", s: "Hagelt en dondert het in februari, dan mag men rekenen op een mooie herfst." },
    { d: "13 februari", s: "Is februari guur en koud, dan wordt de zomer een goudmijn genoemd." },
    { d: "14 februari", s: "Ligt de wind in februari stil, dan komt hij zeker in april." },
    { d: "15 februari", s: "Maakt februari een brugge sterk en straf, maart breekt het weer af." },
    { d: "16 februari", s: "Sint-Apollonia (9 feb) koud en wit, betekent dat er nog veel winter in zit." },
    { d: "17 februari", s: "Aswoensdag nat, de boer wordt zijn oogst zat." },
    { d: "18 februari", s: "Sint-Valentijn (14 feb) zacht en fijn, zal het een vroege lente zijn." },
    { d: "19 februari", s: "Als februari de muggen dansen, krijgt de winter nog grote kansen." },
    { d: "20 februari", s: "Februari nat, geeft een gevuld vat." },
    { d: "21 februari", s: "Sint-Pieter (22 feb) op het ijs, Sint-Pieter van het ijs." },
    { d: "22 februari", s: "Is het op Sint-Pieter koud, de winter houdt nog veertig dagen stand met hout." },
    { d: "23 februari", s: "Sint-Matthias (24 feb) breekt het ijs, heeft hij geen ijs, dan maakt hij ijs." },
    { d: "24 februari", s: "Regen op Sint-Matthias, brengt weinig goeds in de tas." },
    { d: "25 februari", s: "Februari warm, maakt de boer arm." },
    { d: "26 februari", s: "Heeft februari geen kou en wind, april ons met sneeuw bemint." },
    { d: "27 februari", s: "Als het in februari hard vriest, de boer niet snel zijn moed verliest." },
    { d: "28 februari", s: "Droge februari, natte augustus." },
       // --- MAART ---
    { d: "1 maart", s: "Maart roert zijn staart, april doet wat hij wil." },
    { d: "2 maart", s: "Een droge maart en een natte april, is de boeren naar hun wil." },
    { d: "3 maart", s: "Niet te droog, niet te nat, dan vult maart een duchtig vat." },
    { d: "4 maart", s: "Maartse buien die beduien, dat de zomer aan komt kruien." },
    { d: "5 maart", s: "Donder in maart, vorst in april." },
    { d: "6 maart", s: "Brengt maart storm en wind, de sikkel is de boer gezind." },
    { d: "7 maart", s: "Danst het lammetje in maart, april pakt het bij de staart." },
    { d: "8 maart", s: "Lentemaands ruwheid geeft zomermaands luwheid." },
    { d: "9 maart", s: "Een groene maart, een vette weide." },
    { d: "10 maart", s: "Zoveel nevels in maart, zoveel regens na Pasen." },
    { d: "11 maart", s: "Sint-Jozef (19 maart) helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "12 maart", s: "Als het waait op Sint-Benedictus (21 maart), waait het nog veertig dagen." },
    { d: "13 maart", s: "Maart koud, de zomer van goud." },
    { d: "14 maart", s: "Als maart wast als een leeuw, gaat zij weg als een lam." },
    { d: "15 maart", s: "Een natte maart is de boeren een kwade kaart." },
    { d: "16 maart", s: "Wat maart niet wil, neemt april." },
    { d: "17 maart", s: "Heeft maart koude nachten, men moet een warme zomer verwachten." },
    { d: "18 maart", s: "Als het dondert op Sint-Jozefsdag, men veel koren verwachten mag." },
    { d: "19 maart", s: "Zoveel dauw in maart, zoveel vorst in mei." },
    { d: "20 maart", s: "Maartse zon doet de sneeuw smelten als sneeuw voor de zon." },
    { d: "21 maart", s: "Is maart guur en koud, de boer bouwt op zijn hout." },
    { d: "22 maart", s: "Als maart huilt en raast, de boer zijn zorgen wegblaast." },
    { d: "23 maart", s: "Sint-Geertruid (17 maart) breekt de grond, zij maakt de winter gezond." },
    { d: "24 maart", s: "Maart droog, mei nat, geeft veel in het vat." },
    { d: "25 maart", s: "Als maart lacht, de boer op zijn hoede wees." },
    { d: "26 maart", s: "Een stormachtige maart brengt een vruchtbaar jaar." },
    { d: "27 maart", s: "Maart stof op de wegen, brengt de boer grote zegen." },
    { d: "28 maart", s: "Als de kievit in maart al eieren legt, is het weer met de lente slecht." },
    { d: "29 maart", s: "Maart koud en nat, vult de schuur maar niet het vat." },
    { d: "30 maart", s: "Regen in de lentemaand, maakt de boer dikwijls beschaamd." },
    { d: "31 maart", s: "Als maart eindigt met zonneschijn, zal april des te wilder zijn." },
    // --- APRIL ---
    { d: "1 april", s: "April doet wat hij wil, maar mei doet er ook nog wat bij." },
    { d: "2 april", s: "Is april helder en rein, dan zal mei des te wilder zijn." },
    { d: "3 april", s: "April veel regen brengt grote zegen." },
    { d: "4 april", s: "Aprilvlokjes brengen meiklokjes." },
    { d: "5 april", s: "De vrouwen en aprillen, ze hebben beide hun grillen." },
    { d: "6 april", s: "Al doet april ons mooi weer aanschouwen, we kunnen hem niet vertrouwen." },
    { d: "7 april", s: "Het groen des velds het oog bekoort, doch zelden houdt april haar woord." },
    { d: "8 april", s: "April koud en nat, vult de schuur en ook het vat." },
    { d: "9 april", s: "Op een natte april volgt een droge juni." },
    { d: "10 april", s: "Valt er in april veel nat, dan zwemt de boer op zijn eigen pad." },
    { d: "11 april", s: "Sint-Vincent (5 april) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "12 april", s: "Heeft april veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "13 april", s: "April warm, maakt de boer arm." },
    { d: "14 april", s: "Als april blaast op zijn hoorn, is het goed voor gras en koren." },
    { d: "15 april", s: "Valt er sneeuw in april, de winter nog niet wijken wil." },
    { d: "16 april", s: "Valt aprilwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "17 april", s: "Een droge april is niet de boeren hun wil." },
    { d: "18 april", s: "Sint-Valerius (14 april) koud en nat, brengt geen koren in het vat." },
    { d: "19 april", s: "Aprilse grillen, men moet ze niet willen." },
    { d: "20 april", s: "Als de zwaluw in april al komt, de zomer vroeg in bloei staat." },
    { d: "21 april", s: "Sint-Anselmus (21 april) droog en fijn, geeft hoop op goede wijn." },
    { d: "22 april", s: "Aprilse zon en aprilse regen, brengen de natuur grote zegen." },
    { d: "23 april", s: "Sint-George (23 april) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "24 april", s: "Als april begins met zonneschijn, zal de herfst vol druiven zijn." },
    { d: "25 april", s: "April koud en guur, maakt het spek op de zolder duur." },
    { d: "26 april", s: "Als het regent op Sint-Markus (25 april), is de oogst aan het koren schaars." },
    { d: "27 april", s: "Aprilse sneeuw doet de planten geen zeer, maar brengt rijke vruchten weer." },
    { d: "28 april", s: "Is april een wintermaand, dan is de zomer zeer beraamd." },
    { d: "29 april", s: "April nat, mei koel, maakt de boeren een heel goed gevoel." },
    { d: "30 april", s: "Eindigt april met zachte regen, dan brengt mei ons grote zegen." },
       // --- MEI ---
    { d: "1 mei", s: "Als het regent in mei, is april pas echt voorbij." },
    { d: "2 mei", s: "Mei koel en nat, vult de schuur en ook het vat." },
    { d: "3 mei", s: "Een droge mei geeft een vette wei, maar de boer wil ook regen erbij." },
    { d: "4 mei", s: "Morgenrood in de meimaand brengt dikwijls water in de sloot." },
    { d: "5 mei", s: "Avondrood in de lentetijd geeft mooi weer voor een lange tijd." },
    { d: "6 mei", s: "Als de zwaluwen in mei laag vliegen, zal het weer ons niet bedriegen: er komt regen." },
    { d: "7 mei", s: "Kring om de maan in de meise nacht, heeft vaak snel regen gebracht." },
    { d: "8 mei", s: "Onweer in mei maakt de boeren blij, het koren groeit dan in de rij." },
    { d: "9 mei", s: "Als mei begint met zonneschijn, zal de herfst vol zoete vruchten zijn." },
    { d: "10 mei", s: "Meise regen is voor het jonge gewas een grote zegen." },
    { d: "11 mei", s: "Sint-Mamertus (11 mei) koud en grijs, brengt de jonge bloesem van de wijs." },
    { d: "12 mei", s: "Sint-Pancratius (12 mei) koud en nat, brengt geen koren in het vat." },
    { d: "13 mei", s: "Sint-Servaas (13 mei) moet de winter jagen, of we krijgen gure dagen." },
    { d: "14 mei", s: "Sint-Bonifatius (14 mei) sluit de rij, na de IJsheiligen is de vorst voorbij." },
    { d: "15 mei", s: "Sint-Sophia (15 mei) brengt vaak nog kou, zij zet de bloemen in de kou." },
    { d: "16 mei", s: "Is mei te vroeg warm en zacht, de zomer vaak koude nachten bracht." },
    { d: "17 mei", s: "Hoor je de donder in het groene woud, dan blijft het weer nog langdurig koud." },
    { d: "18 mei", s: "Meise mist heeft de boer in his plannen misgist." },
    { d: "19 mei", s: "Als mei de bomen vol in het groen doen staan, zal de oogst voorspoedig gaan." },
    { d: "20 mei", s: "Mei helder en rein, zal een voorbode van een droge zomer zijn." },
    { d: "21 mei", s: "Een zachte mei brengt een rijke wei en maakt de koetjes blij." },
    { d: "22 mei", s: "Meise buien breken de laatste kou en zetten de natuur uit de rouw." },
    { d: "23 mei", s: "Eind mei warme dagen, zal de zomer ons zeker behagen." },
    { d: "24 mei", s: "Als mei begint met koude wind, men in de zomer weinig warmte vindt." },
    { d: "25 mei", s: "Regent het op Sint-Urbanusdag (25 mei), men een goede wijnoogst verwachten mag." },
    { d: "26 mei", s: "Sint-Urbanus helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "27 mei", s: "Als de eiken bloeien voor de mei, is het jaar van graanzorgen vrij." },
    { d: "28 mei", s: "Meise zon doet het koren goed groeien en de bloemen weelderig bloeien." },
    { d: "29 mei", s: "Is mei nat, dan heeft het spek op het vat." },
    { d: "30 mei", s: "Veel dauw in de meimorgen, verdrijft de boer zijn zorgen." },
    { d: "31 mei", s: "Eindigt mei koel en nat, geeft dat koren op het pad." },
    // --- JUNI ---
    { d: "1 juni", s: "Juni vochtig, koel en fris, maakt dat de schuur straks vol met koren is." },
    { d: "2 juni", s: "Juni nat, de boer wordt zijn hooi duchtig zat." },
    { d: "3 juni", s: "Juni warm en droog, houdt de oogstmoed bij de landman hoog." },
    { d: "4 juni", s: "Onweer in de vroege juni-maand, brengt een vruchtbaar jaar aan." },
    { d: "5 juni", s: "Juni stof op de wegen, brengt de natuur grote zegen." },
    { d: "6 juni", s: "Regen in de vroege zomerzon, vult de waterput en de bron." },
    { d: "7 juni", s: "Als juni begint met zonneschijn, zal de zomer vol warmte zijn." },
    { d: "8 juni", s: "Sint-Medardus (8 juni) nat, geeft veertig dagen nat op het pad." },
    { d: "9 juni", s: "Sint-Medardus klaar en helder, vult het vat en ook de kelder." },
    { d: "10 juni", s: "Onweer in juni vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "11 juni", s: "Als het regent op Sint-Barnabas (11 juni), zwemt het koren in een plas." },
    { d: "12 juni", s: "Juniwind uit het noorden, houdt de echte warmte uit alle oorden." },
    { d: "13 juni", s: "Regen in juni is de boeren hun zegen, maar te veel zet het gewas tegen." },
    { d: "14 juni", s: "Is juni warm en helder, vult de landman zijn kelder." },
    { d: "15 juni", s: "Zware dauw in de zomermaand, houdt het weer standvastig en stand." },
    { d: "16 juni", s: "Als de koekoek na Sint-Jan nog zingt, de zomer niet veel goeds meer brengt." },
    { d: "17 juni", s: "Juniregen, korenzegen, alles komt de natuur gelegen." },
    { d: "18 juni", s: "Als juni nat is, klaagt de landman niet om droogte." },
    { d: "19 juni", s: "Juni zacht, winter met macht." },
    { d: "20 juni", s: "Juni koel en guur, maakt het graan op de markt duur." },
    { d: "21 juni", s: "Met Sint-Aloysius (21 juni) begint de zon te keren, het weer zal ons wat leren." },
    { d: "22 juni", s: "Juni droog en heet, maakt de boer heel veel zweet." },
    { d: "23 juni", s: "Juniregen brengt geen zegen, als hij valt in de hooioogst tegen." },
    { d: "24 juni", s: "Sint-Jan (24 juni) nat, geeft een slecht gevuld korenvat." },
    { d: "25 juni", s: "Als het regent op Sint-Jan, heeft men er dertig dagen van." },
    { d: "26 juni", s: "Vóór Sint-Jan mag men om regen bidden, daarna komt hij ongeroepen in ons midden." },
    { d: "27 juni", s: "Sint-Jan helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "28 juni", s: "Als juni eindigt met wind en regen, is dat voor de boomvruchten geen zegen." },
    { d: "29 juni", s: "Sint-Pieter en Paulus (29 juni) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "30 juni", s: "Eindigt juni met warme dagen, zal de zomertijd ons behagen." },
        // --- JULI ---
    { d: "1 juli", s: "Juli warm en droog, houdt de herfst de moed hoog." },
    { d: "2 juli", s: "Maria Visitatie (2 juli) nat, geeft dertig dagen regen op het pad." },
    { d: "3 juli", s: "Valt er in juli veel nat, dan zwemt de boer op zijn eigen pad." },
    { d: "4 juli", s: "Juli helder, koud en rein, zal een droog najaar zijn." },
    { d: "5 juli", s: "Onweer in juli brengt een vruchtbaar korenjaar." },
    { d: "6 juli", s: "Juli helder en rein, zal een zegen voor de oogst zijn." },
    { d: "7 juli", s: "Als juli begint met zonneschijn, zal de zomer vol echte warmte zijn." },
    { d: "8 juli", s: "Julidroogte, de landman houdt zijn hoofd in de hoogte." },
    { d: "9 juli", s: "Regen in juli is voor het koren geen zegen." },
    { d: "10 juli", s: "Is juli warm en helder, vult de boer zijn kelder." },
    { d: "11 juli", s: "Julistof op de wegen, brengt de natuur weinig zegen." },
    { d: "12 juli", s: "Onweer in juli vroeg in de morgen, brengt de boer grote oogstzorgen." },
    { d: "13 juli", s: "Is juli heet en droog, dan houdt de winter een streng betoog." },
    { d: "14 juli", s: "Als juli nat is, klaagt de landman duchtig." },
    { d: "15 juli", s: "Juli zacht, winter met macht." },
    { d: "16 juli", s: "Het groen van de velden het oog bekoort, doch zelden houdt juli her woord." },
    { d: "17 juli", s: "Juli koel, een mager oogstgevoel." },
    { d: "18 juli", s: "Eindigt juli met warme dagen, zal de vroege herfst ons behagen." },
    { d: "19 juli", s: "Sint-Vincentius (19 juli) klaar en helder, vult het vat en ook de kelder." },
    { d: "20 juli", s: "Sint-Margaretha (20 juli) nat, geeft dertig dagen nat op het pad." },
    { d: "21 juli", s: "Juliregen, geen korenzegen." },
    { d: "22 juli", s: "Sint-Magdalena (22 juli) droog, houdt de graanprijs in de hoog." },
    { d: "23 juli", s: "Als juli begint met wind en felle regen, is dat voor de aardappels geen zegen." },
    { d: "24 juli", s: "Heeft juli veel zonneschijn, de fruitoogst zal des te beter zijn." },
    { d: "25 juli", s: "Sint-Jacob (25 juli) helder en warm, maakt de boer rijk en niet arm." },
    { d: "26 juli", s: "Als het regent op Sint-Jacob, is de oogst aan het koren schaars." },
    { d: "27 juli", s: "Als juli blaast op zijn hoorn, is het slecht voor gras i koren." },
    { d: "28 juli", s: "Valt juliwind uit het noorden, de koelte houdt aan op alle oorden." },
    { d: "29 juli", s: "Een droge juli is wel de boeren hun wil." },
    { d: "30 juli", s: "Juli koel en nat, geeft weinig spek op het vat." },
    { d: "31 juli", s: "Eindigt juli met zachte regen, dan brengt dat de boer grote zegen." },
    // --- AUGUSTUS ---
    { d: "1 augustus", s: "Augustus warm en droog, houdt de herfst de moed hoog." },
    { d: "2 augustus", s: "Geeft begin augustus veel zonneschijn, dan zal het een strenge winter zijn." },
    { d: "3 augustus", s: "Als augustus zonder regen heen zou gaan, zou de boer in armoede staan." },
    { d: "4 augustus", s: "Onweer in augustus vroeg in de morgen, brengt de landbouw grote zorgen." },
    { d: "5 augustus", s: "Als de eerste week van augustus heet is, de winter wit, lang en koud gewis is." },
    { d: "6 augustus", s: "Augustusnoordenwind brengt standvastig en mooi weer met gezind." },
    { d: "7 augustus", s: "Augustus helder, koud en rein, zal een droog najaar zijn." },
    { d: "8 augustus", s: "Onweer in de oogstmaand brengt een vruchtbaar najaar." },
    { d: "9 augustus", s: "Augustus koel en guur, maakt het haardhout vroeg duur." },
    { d: "10 augustus", s: "Sint-Laurens (10 aug) helder en warm, maakt de boer rijk en niet arm." },
    { d: "11 augustus", s: "Als het regent op Sint-Laurens, is de oogst aan het koren schaars." },
    { d: "12 augustus", s: "Augustus droog, de landman houdt zijn hoofd omhoog." },
    { d: "13 augustus", s: "Regen in augustus is voor de bomen en het fruit een zegen." },
    { d: "14 augustus", s: "Is augustus warm en helder, vult de boer zijn winterkelder." },
    { d: "15 augustus", s: "Maria Hemelvaart (15 aug) helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "16 augustus", s: "Augustusstof op de wegen, brengt de natuur weinig zegen." },
    { d: "17 augustus", s: "Augustusregen, geen korenzegen." },
    { d: "18 augustus", s: "Als augustus nat is, klaagt de landman duchtig over schimmel." },
    { d: "19 augustus", s: "Augustus zacht, winter met macht." },
    { d: "20 augustus", s: "Augustus koel, geeft de natuur een vroeg herfstgevoel." },
    { d: "21 augustus", s: "Eindigt augustus met warme dagen, zal de vroege winter ons gaan plagen." },
    { d: "22 augustus", s: "Sint-Laurens klaar en helder, vult het vat en ook de kelder." },
    { d: "23 augustus", s: "Augustus nat, geeft spek op het vat." },
    { d: "24 augustus", s: "Sint-Bartholomeüs (24 aug) helder en rein, zal een mooie nazomer zijn." },
    { d: "25 augustus", s: "Als het regent op Sint-Bartel, is de herfstmaand vaak heel dartel." },
    { d: "26 augustus", s: "Heeft augustus veel zonneschijn, de winter zal des te kouder zijn." },
    { d: "27 augustus", s: "Augustus warm, maakt de boer dikwijls arm." },
    { d: "28 augustus", s: "Als augustus blaast op zijn hoorn, bevriest vroeg het koren." },
    { d: "29 augustus", s: "Valt augustuswind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "30 augustus", s: "Een droge oogstmaand is voor de landman een zegen waard." },
    { d: "31 augustus", s: "Eindigt augustus met felle kou, bouwt men op een goede fruitoogst." },
       // --- SEPTEMBER ---
    { d: "1 september", s: "Als september begint met warmte en zon, vult de boer met plezier zijn ton." },
    { d: "2 september", s: "Als het regent op Sint-Giel (1 sept), waait het nog veertig dagen met gevoel." },
    { d: "3 september", s: "September helder en rein, zal het volgend jaar vol vruchten zijn." },
    { d: "4 september", s: "Onweer in septembernacht, brengt dikwijls een winter zacht." },
    { d: "5 september", s: "Septemberregen op het zaad, is een zaak die de boer behaagt." },
    { d: "6 september", s: "Als september begint met zonneschijn, zal de herfst vol zoete druiven zijn." },
    { d: "7 september", s: "Is september droog en warm, dan klaagt de landman niet om zijn darm." },
    { d: "8 september", s: "Regen op Maria Geboorte (8 sept), brengt louter gaten in de oogstsoorte." },
    { d: "9 september", s: "Is september warm en helder, vult de boer zijn wijnkelder." },
    { d: "10 september", s: "Septembermist brengt vaak vorst in de kist." },
    { d: "11 september", s: "Onweer in september vroeg in de morgen, brengt de boer voor de winter zorgen." },
    { d: "12 september", s: "Vallen de bladeren vroeg in de herfstmaand af, dan is de winter mild van straf." },
    { d: "13 september", s: "Als september nat is en guur, wordt het hout voor de kachel duur." },
    { d: "14 september", s: "Sint-Cornelius zacht, winter met macht." },
    { d: "15 september", s: "September koel, geeft voor de herfst een mager gevoel." },
    { d: "16 september", s: "Eindigt september met warme dagen, zal de winter ons later gaan plagen." },
    { d: "17 september", s: "Sint-Lambertus (17 sept) klaar en helder, vult het vat en ook de kelder." },
    { d: "18 september", s: "September nat, geeft de wandelaar een drassig pad." },
    { d: "19 september", s: "Als september begint met felle wind, men in de Vis weinig ijs vindt." },
    { d: "20 september", s: "Heeft september veel zonneschijn, de herfst zal vol met warmte zijn." },
    { d: "21 september", s: "Is het warm op Sint-Mattheüs (21 sept), dan blijft het weer nog lang sereen." },
    { d: "22 september", s: "Als september blaast op zijn hoorn, staat het land vol met nieuw koren." },
    { d: "23 september", s: "Valt septemberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "24 september", s: "Een droge septembermaand is goud waard voor het vee op de weide." },
    { d: "25 september", s: "Treffen we in september veel spinnenwebben aan, dan zal de nazomer lang aanhouden." },
    { d: "26 september", s: "Trekt de zwaluw vroeg in september weg, dan is een vroege winter het gezeg." },
    { d: "27 september", s: "Als septemberwind uit het zuiden waait, wordt het nieuwe koren goed gezaaid." },
    { d: "28 september", s: "Veel eikels in de herfstmaand, brengt een winter wit en zwaar." },
    { d: "29 september", s: "Als de herfstmaand helder eindigt met Sint-Michiel, de winter vroeg op het ijs viel." },
    { d: "30 september", s: "Septemberregen op de stoppels, brengt de boer veel melknoppels." },
    // --- OKTOBER ---
    { d: "1 oktober", s: "Blinkt oktober in zonnegoud, de winter volgt dan snel en koud." },
    { d: "2 oktober", s: "Is oktober warm en fijn, het zal een scherpe winter zijn." },
    { d: "3 oktober", s: "Oktober veel gedruis, dan is het met het najaar niet pluis." },
    { d: "4 oktober", s: "Oktober warm en droog, houdt de winter de moed hoog." },
    { d: "5 oktober", s: "Als oktober de bladeren lang laat hangen, mag men voor een strenge winter bangen." },
    { d: "6 oktober", s: "Als het regent op Sint-Fides (6 okt), zwemt de herfst in een diepe plas." },
    { d: "7 oktober", s: "Oktober helder en rein, zal een voorbode van veel sneeuw zijn." },
    { d: "8 oktober", s: "Onweer in de wijnmaand brengt een grillig en koud voorjaar." },
    { d: "9 oktober", s: "Oktober koel en guur, maakt het haardhout in de schuur duur." },
    { d: "10 oktober", s: "Als oktober begint met zonneschijn, zal de winter vol sneeuwval zijn." },
    { d: "11 oktober", s: "Oktober droog, de landman houdt zijn hoofd omhoog." },
    { d: "12 oktober", s: "Regen in oktober is voor de bomen een grote zegen." },
    { d: "13 oktober", s: "Is oktober warm en helder, vult de boer zijn winterkelder." },
    { d: "14 oktober", s: "Oktoberstof op de wegen, brengt de natuur weinig zegen." },
    { d: "15 oktober", s: "Hoor je de donder in oktober luiden, dat zal een gure winter beduiden." },
    { d: "16 oktober", s: "Sint-Gallus (16 okt) droog en fijn, geeft hoop op goede wijn." },
    { d: "17 oktober", s: "Als oktober nat is en koud, haalt de boer extra veel hout." },
    { d: "18 oktober", s: "Sint-Lucas (18 okt) warm en zacht, heeft vaak een gouden herfst gebracht." },
    { d: "19 oktober", s: "Oktober koel, geeft de natuur een winters gevoel." },
    { d: "20 oktober", s: "Eindigt oktober met warme dagen, zal de winter ons in januari plagen." },
    { d: "21 oktober", s: "Is oktobermaand warm en nat, dan krijgt de winter een late spat." },
    { d: "22 oktober", s: "Oktober nat, geeft spek op het vat." },
    { d: "23 oktober", s: "Als oktober begint met wind en felle regen, is dat voor de winter geen zegen." },
    { d: "24 oktober", s: "Heeft oktober veel felle zonneschijn, de winter zal des te kouder zijn." },
    { d: "25 oktober", s: "Oktober warm, maakt de arts rijk en de boer arm." },
    { d: "26 oktober", s: "Als oktober blaast op zijn hoorn, bevriest het pas gezaaide koren." },
    { d: "27 oktober", s: "Valt oktoberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "28 oktober", s: "Sint-Simon en Judas (28 okt) brengen de winter in het land met gure winden." },
    { d: "29 oktober", s: "Oktober koud en nat, vult the schuur maar niet het vat." },
    { d: "30 oktober", s: "Vriest het eind oktober al dat het kraakt, de winter vroeg zijn intrede maakt." },
    { d: "31 oktober", s: "Als in oktober de bladeren snel vallen, zal de winter hard knallen." },
     // --- NOVEMBER ---
    { d: "1 november", s: "Brengt Allerheiligen (1 nov) sneeuw en wind, de winter ons heel vroeg bemint." },
    { d: "2 november", s: "Allerzielen (2 nov) nat en koud, brengt de winter in het woud." },
    { d: "3 november", s: "November warm en droog, houdt de winter zijn koude moed hoog." },
    { d: "4 november", s: "Is november vroeg in de kou, dan zit men in de lente in de rouw." },
    { d: "5 november", s: "Als het waait op begin november, waait het door tot in december." },
    { d: "6 november", s: "November helder, koud en rein, zal een droge winter zijn." },
    { d: "7 november", s: "Onweer in november over het land, brengt de winter uit de band." },
    { d: "8 november", s: "November koel and nat, maakt de wegen tot een modderpad." },
    { d: "9 november", s: "Als november begint met veel zonneschijn, zal de winter heel streng zijn." },
    { d: "10 november", s: "Sint-Maartensavond (10 nov) helder en grijs, houdt de winter op het ijs." },
    { d: "11 november", s: "Sint-Maarten (11 nov) helder en warm, maakt de boer rijk en niet arm." },
    { d: "12 november", s: "Als het regent op Sint-Maarten, is de winter in de kaarten." },
    { d: "13 november", s: "Novemberstof op de wegen, brengt de landman geen zegen." },
    { d: "14 november", s: "Zwaait november met zijn staart, de winter is een vroege gast bij de haard." },
    { d: "15 november", s: "November regen, brengt het komende jaar geen zegen." },
    { d: "16 november", s: "Als november nat is en koud, de winter standhoudt met veel hout." },
    { d: "17 november", s: "November zacht en nat, geeft een slecht gevuld vat." },
    { d: "18 november", s: "November koel, geeft een mager en guur gevoel." },
    { d: "19 november", s: "Eindigt november met warme dagen, zal de sneeuw ons in december plagen." },
    { d: "20 november", s: "Als de winter in november niet vriezen wil, vriest het in maart of april." },
    { d: "21 november", s: "Maria Presentatie (21 nov) helder en klaar, voorspelt een streng ijsjaar." },
    { d: "22 november", s: "Als november begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "23 november", s: "Sint-Clemens (23 nov) herbergt de winter, hij brengt sneeuw en wind mee." },
    { d: "24 november", s: "Heeft november felle zon, dan bevriest de waterbron." },
    { d: "25 november", s: "Sint-Catharina (25 nov) helder en fijn, de winter zal heel scherp zijn." },
    { d: "26 november", s: "Valt novemberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "27 november", s: "Een droge slachtmaand is voor de boer een zegen waard." },
    { d: "28 november", s: "November koud en guur, maakt het spek op de zolder duur." },
    { d: "29 november", s: "Als de velden in november groen blijven staan, zal de winter laat overgaan." },
    { d: "30 november", s: "Sint-Andries (30 nov) helder en fijn, belooft een goed jaar voor de wijn." },
    // --- DECEMBER ---
    { d: "1 december", s: "Als december begint met felle kou, bouwt men op een oogst waar men op bouwen kan." },
    { d: "2 december", s: "December warm en droog, houdt de lente de moed hoog." },
    { d: "3 december", s: "De dagen lengen, de nachten strengen na een koude decembersfeer." },
    { d: "4 december", s: "Sint-Barbara (4 dec) brengt de kou, zij zet de bloesem in de kou." },
    { d: "5 december", s: "Sinterklaas (5 dec) koud en rein, zal een witte winter zijn." },
    { d: "6 december", s: "Onweer in decembermaand over het woud, maakt de zomer dikwijls koud." },
    { d: "7 december", s: "December koel en nat, vult de sloten maar niet het vat." },
    { d: "8 december", s: "Als december begint met felle zonneschijn, zal het een zware winter zijn." },
    { d: "9 december", s: "December droog, de landman houdt zijn moed omhoog." },
    { d: "10 december", s: "Regen in de wintermaand, maakt de boer dikwijls beschaamd." },
    { d: "11 december", s: "Is december warm en helder, vult de winter de kelder." },
    { d: "12 december", s: "Decemberstof op de wegen, brengt de natuur weinig zegen." },
    { d: "13 december", s: "Sint-Lucia (13 dec) lengt de dag zo ver een vlooienbeet wezen mag." },
    { d: "14 december", s: "Onweer in december vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "15 december", s: "December regen, brengt het koren geen zegen." },
    { d: "16 december", s: "Als december nat is en koud, de schaatser op veel ijs bouwt." },
    { d: "17 december", s: "December zacht, winter met macht." },
    { d: "18 december", s: "December koel, een mager gevoel voor de winter." },
    { d: "19 december", s: "Eindigt december met warme dagen, zal de winter ons in januari plagen." },
    { d: "20 december", s: "Zijn de nachten in december kort en grijs, men gaat dan niet gerust op reis." },
    { d: "21 december", s: "Sint-Thomas (21 dec) de kortste dag, brengt ijs en sneeuw als hij mag." },
    { d: "22 december", s: "Als het waait op Sint-Thomasnacht, waait het nog veertig dagen met kracht." },
    { d: "23 december", s: "Heeft december veel felle kou, de natuur staat in de kou." },
    { d: "24 december", s: "Kersavond klaar en helder, vult de schuur en ook het vat." },
    { d: "25 december", s: "Een groene kerst brengt een witte en koude Pasen." },
    { d: "26 december", s: "Als Sint-Stefanus (26 dec) veel wind brengt, de boer zijn koren met zand mengt." },
    { d: "27 december", s: "Valt decemberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "28 december", s: "Onschuldige Kinderen (28 dec) koud en nat, vult het komende jaar het vat." },
    { d: "29 december", s: "December koel en nat, geeft de landman een modderig pad." },
    { d: "30 december", s: "Als december eindigt met felle kou, bouwt men op een goede fruitoogst." },
    { d: "31 december", s: "Vriest het op Sint-Silvester (31 dec) dat het kraakt, nieuwjaarsdag een goede start maakt." },
    { d: "29 februari", s: "Als februari negenentwintig dagen telt, schrikkelt de natuur mee in het veld." }
];

