const dagelijkseFeitjes = [
    // --- JANUARI (1 t/m 31) ---
    { d: "1 januari", s: "Als januari begint met een goede sfeer, brengt de rest van het jaar vaak mooi weer." },
    { d: "2 januari", s: "Januari zonder regen is voor de boerenstand een zegen." },
    { d: "3 januari", s: "Geeft januari een sneewtapijt, dan zijn we gauw de winter kwijt." },
    { d: "4 januari", s: "Als de kat in januari in de zon ligt, ligt ze in februari achter de kachel." },
    { d: "5 januari", s: "Als de days lengen, begint the winter te strengen." },
    { d: "6 januari", s: "Draagt januari een sneeuwwit kleed, wordt de zomer zeer heet." },
    { d: "7 januari", s: "Knapt januari niet van kou, dan zit men in de oogst in de rouw." },
    { d: "8 januari", s: "Is januari guur en koud, dan wordt de boer een rijke man genoemd." },
    { d: "9 januari", s: "Heeft januari felle kou, then volgt een zomer waar men op bouwen kan." },
    { d: "10 januari", s: "Als het in januari mistig is, dan is een natte lente gewis." },
    { d: "11 januari", s: "Brengt januari felle koude, de winter zal niet lang meer houden." },
    { d: "12 januari", s: "Als januari de vorst niet brengt, de zomer vaak met regen mengt." },
    { d: "13 januari", s: "Sint-Hilarius (13 jan) met veel kou, brengt de winter in het nauw." },
    { d: "14 januari", s: "Als de winter in januari niet vriezen wil, dan vriest het in maart of april." },
    { d: "15 januari", s: "Januari koud en nat, vult de schuur en ook het vat." },
    { d: "16 januari", s: "Sint-Anthonius (17 jan) klaar en helder, vult het vat en ook de kelder." },
    { d: "17 januari", s: "Als het vriest op Sint-Sebastiaan (20 jan), dan zal de winter nog lang aanhouden." },
    { d: "18 januari", s: "Sint-Agnes (21 jan) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "19 januari", s: "Is januari zacht en nat, dan krijgt de winter een late spat." },
    { d: "20 januari", s: "Vincentius (22 jan) zonneschijn, geeft veel koren en goede wijn." },
    { d: "21 januari", s: "Als het op Sint-Paulus (25 jan) helder is, is het jaar van granen gewis." },
    { d: "22 januari", s: "Januari zacht, winter met macht." },
    { d: "23 januari", s: "Als januari de muggen zwermen, moet men in maart de schapen beschermen." },
    { d: "24 januari", s: "Is januari warm en nat, dan raakt de boer zijn oogst duchtig zat." },
    { d: "25 januari", s: "Klaar weer op Sint-Paulusnacht, brengt het jaar een goede oogst met macht." },
    { d: "26 januari", s: "Veel sneeuw in de wintermaand, veel hooi op de weide." },
    { d: "27 januari", s: "Als januari geen vorst wil dragen, komt die in de lentedagen." },
    { d: "28 januari", s: "Heeft januari felle zon, dan droogt de boer his waterbron." },
    { d: "29 januari", s: "Als het in de wintermaand hard waait, wordt het koren goed gezaaid." },
    { d: "30 januari", s: "Januari koud en guur, maakt het spek op de zolder duur." },
    { d: "31 januari", s: "Als de eerste maand ons vriezen laat, de zomer vroeg in bloei staat." },
        // --- FEBRUARI (32 t/m 59) ---
    { d: "1 februari", s: "In de sprokkelmaand koud en guur, is de winter van korte duur." },
    { d: "2 februari", s: "Maria Lichtmis (2 feb) helder en klaar, maakt de boer tot bedelaar." },
    { d: "3 februari", s: "Lichtmis in de klaver, Pasen in de sneeuw." },
    { d: "4 februari", s: "Als het op Lichtmis helder is, krijgt de winter een staart gewis." },
    { d: "5 februari", s: "Februari regen, is de landman zijn zegen." },
    { d: "6 februari", s: "Februari zacht en stil, dan komt de noordenwind in april." },
    { d: "7 februari", s: "Februari zonder storm, in april is hij in vorm." },
    { d: "8 februari", s: "Gaan de mieren al aan 't sparen, zullen kou en vorst gewis niet sparen." },
    { d: "9 februari", s: "Geeft de sprokkelmaand de winter niet, is hij voor Pasen in het verschiet." },
    { d: "10 februari", s: "Geeft februari muggendans, voor maart is er een slechte kans." },
    { d: "11 februari", s: "Groeit in februari het gras, met Pasen een dikke jas." },
    { d: "12 februari", s: "Hagelt en dondert het in februari, dan mag men rekenen op een mooie herfst." },
    { d: "13 februari", s: "Is februari guur en koud, dan wordt de zomer een goudmijn genoemd." },
    { d: "14 februari", s: "Ligt de wind in februari stil, dan komt hij zeker in april." },
    { d: "15 februari", s: "Maakt februari een brugge sterk en straf, maart breekt het weer af." },
    { d: "16 februari", s: "Sint-Apollonia (9 feb) koud en wit, betekent dat er nog veel winter in zit." },
    { d: "17 februari", s: "Aswoensdag nat, de boer wordt zijn oogst zat." },
    { d: "18 februari", s: "Sint-Valentijn (14 feb) zacht en fijn, zal het een vroege lente zijn." },
    { d: "19 februari", s: "Als februari de muggen dansen, krijgt de winter nog grote kansen." },
    { d: "20 februari", s: "Februari nat, geeft een gevuld vat." },
    { d: "21 februari", s: "Sint-Pieter (22 feb) op het ijs, Sint-Pieter van het ijs." },
    { d: "22 februari", s: "Is het op Sint-Pieter koud, de winter houdt nog veertig dagen stand met hout." },
    { d: "23 februari", s: "Sint-Matthias (24 feb) breekt het ijs, heeft hij geen ijs, dan maakt hij ijs." },
    { d: "24 februari", s: "Regen op Sint-Matthias, brengt weinig goeds in de tas." },
    { d: "25 februari", s: "Februari warm, maakt de boer arm." },
    { d: "26 februari", s: "Heeft februari geen kou en wind, april ons met sneeuw bemint." },
    { d: "27 februari", s: "Als het in februari hard vriest, de boer niet snel zijn moed verliest." },
    { d: "28 februari", s: "Droge februari, natte augustus." },
    // --- MAART (60 t/m 90) ---
    { d: "1 maart", s: "Maart roert zijn staart, april doet wat hij wil." },
    { d: "2 maart", s: "Een droge maart en een natte april, is de boeren naar hun wil." },
    { d: "3 maart", s: "Niet te droog, niet te nat, dan vult maart een duchtig vat." },
    { d: "4 maart", s: "Maartse buien die beduien, dat de zomer aan komt kruien." },
    { d: "5 maart", s: "Donder in maart, vorst in april." },
    { d: "6 maart", s: "Brengt maart storm en wind, the sikkel is de boer gezind." },
    { d: "7 maart", s: "Danst het lammetje in maart, april pakt het bij de staart." },
    { d: "8 maart", s: "Lentemaands ruwheid geeft zomermaands luwheid." },
    { d: "9 maart", s: "Een groene maart, een vette weide." },
    { d: "10 maart", s: "Zoveel nevels in maart, zoveel regens na Pasen." },
    { d: "11 maart", s: "Sint-Jozef (19 maart) helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "12 maart", s: "Als het waait op Sint-Benedictus (21 maart), waait het nog veertig dagen." },
    { d: "13 maart", s: "Maart koud, de zomer van goud." },
    { d: "14 maart", s: "Als maart wast als een leeuw, gaat zij weg als een lam." },
    { d: "15 maart", s: "Een natte maart is de boeren een kwade kaart." },
    { d: "16 maart", s: "Wat maart niet wil, neemt april." },
    { d: "17 maart", s: "Heeft maart koude nachten, men moet een warme zomer verwachten." },
    { d: "18 maart", s: "Als het dondert op Sint-Jozefsdag, men veel koren verwachten mag." },
    { d: "19 maart", s: "Zoveel dauw in maart, zoveel vorst in mei." },
    { d: "20 maart", s: "Maartse zon doet de sneeuw smelten als sneeuw voor de zon." },
    { d: "21 maart", s: "Is maart guur en koud, de boer bouwt op zijn hout." },
    { d: "22 maart", s: "Als maart huilt en raast, de boer zijn zorgen wegblaast." },
    { d: "23 maart", s: "Sint-Geertruid (17 maart) breekt de grond, zij maakt de winter gezond." },
    { d: "24 maart", s: "Maart droog, mei nat, geeft veel in het vat." },
    { d: "25 maart", s: "Als maart lacht, de boer op zijn hoede wees." },
    { d: "26 maart", s: "Een stormachtige maart brengt een vruchtbaar jaar." },
    { d: "27 maart", s: "Maart stof op de wegen, brengt de boer grote zegen." },
    { d: "28 maart", s: "Als de kievit in maart al eieren legt, is het weer met de lente slecht." },
    { d: "29 maart", s: "Maart koud and nat, vult de schuur maar niet het vat." },
    { d: "30 maart", s: "Regen in de lentemaand, maakt de boer dikwijls beschaamd." },
    { d: "31 maart", s: "Als maart eindigt met zonneschijn, zal april des te wilder zijn." },
        // --- APRIL (91 t/m 120) ---
    { d: "1 april", s: "April doet wat hij wil, maar mei doet er ook nog wat bij." },
    { d: "2 april", s: "Is april helder en rein, dan zal mei des te wilder zijn." },
    { d: "3 april", s: "April veel regen brengt grote zegen." },
    { d: "4 april", s: "Aprilvlokjes brengen meiklokjes." },
    { d: "5 april", s: "De vrouwen en aprillen, ze hebben beide hun grillen." },
    { d: "6 april", s: "Al doet april ons mooi weer aanschouwen, 't is evenals fortuin, we kunnen hem niet vertrouwen." },
    { d: "7 april", s: "Het groen des velds het oog bekoort, doch zelden houdt april haar woord." },
    { d: "8 april", s: "April koud en nat, vult de schuur en ook het vat." },
    { d: "9 april", s: "Op een natte april volgt een droge juni." },
    { d: "10 april", s: "Valt er in april veel nat, dan zwemt de boer op zijn eigen pad." },
    { d: "11 april", s: "Sint-Vincent (5 april) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "12 april", s: "Heeft april veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "13 april", s: "April warm, maakt de boer arm." },
    { d: "14 april", s: "Als april blaast op zijn hoorn, is het goed voor gras og koren." },
    { d: "15 april", s: "Valt er sneeuw in april, de winter nog niet wijken wil." },
    { d: "16 april", s: "Valt aprilwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "17 april", s: "Een droge april is niet de boeren hun wil." },
    { d: "18 april", s: "Sint-Valerius (14 april) koud en nat, brengt geen koren in het vat." },
    { d: "19 april", s: "Aprilse grillen, men moet ze niet willen." },
    { d: "20 april", s: "Als de zwaluw in april al komt, de zomer vroeg in bloei staat." },
    { d: "21 april", s: "Sint-Anselmus (21 april) droog en fijn, geeft hoop op goede wijn." },
    { d: "22 april", s: "Aprilse zon en aprilse regen, brengen de natuur grote zegen." },
    { d: "23 april", s: "Sint-George (23 april) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "24 april", s: "Als april begint met zonneschijn, zal de herfst vol druiven zijn." },
    { d: "25 april", s: "April koud en guur, maakt het spek op de zolder duur." },
    { d: "26 april", s: "Als het regent op Sint-Markus (25 april), is de oogst aan het koren schaars." },
    { d: "27 april", s: "Aprilse sneeuw doet de planten geen zeer, maar brengt rijke vruchten weer." },
    { d: "28 april", s: "Is april een wintermaand, dan is de zomer zeer beraamd." },
    { d: "29 april", s: "April nat, mei koel, maakt de boeren een heel goed gevoel." },
    { d: "30 april", s: "Eindigt april met zachte regen, dan brengt mei ons grote zegen." },
    // --- MEI (121 t/m 151) ---
    { d: "1 mei", s: "Mei koel en nat, vult de schuur en ook het vat." },
    { d: "2 mei", s: "Als het regent in mei, is april voorbij." },
    { d: "3 mei", s: "Pancratius, Servatius en Bonifatius (IJsheiligen), zij herbergen de laatste koude nachten." },
    { d: "4 mei", s: "Voor de IJsheiligen (11-13 mei) geen zomerdag, daarna men vorst niet vrezen mag." },
    { d: "5 mei", s: "Avondrood brengt water in de sloot, morgenrood geeft mooi weer aan boord." },
    { d: "6 mei", s: "Kring om de maan, zal in de regen vergaan." },
    { d: "7 mei", s: "Als de zwaluwen laag vliegen, nadert er regen." },
    { d: "8 mei", s: "Een droge mei, een vette weide." },
    { d: "9 mei", s: "Mei warm and droog, houdt de herfst de moed hoog." },
    { d: "10 mei", s: "Onweer in mei, maakt de boeren blij." },
    { d: "11 mei", s: "Als mei begint met zonneschijn, zal de herfst vol druiven zijn." },
    { d: "12 mei", s: "Meise regen is de landman zijn zegen." },
    { d: "13 mei", s: "Is mei te vroeg warm en zacht, de zomer koude nachten bracht." },
    { d: "14 mei", s: "Sint-Urbanus (25 mei) helder en klaar, geeft een heel vruchtbaar wijnjaar." },
    { d: "15 mei", s: "Hoor je de donder in mei, dan maakt dat het hart van de boer heel blij." },
    { d: "16 mei", s: "Mei nat, spek op het vat." },
    { d: "17 mei", s: "Als mei begint met koude wind, men in de zomer weinig warmte vindt." },
    { d: "18 mei", s: "Als de eiken bloeien voor de mei, is het jaar van granen vrij." },
    { d: "19 mei", s: "Meise zon doet het koren groeien, en de bloemen weelderig bloeien." },
    { d: "20 mei", s: "Sint-Mamertus (11 mei) koud en grijs, brengt de bloesem van de wijs." },
    { d: "21 mei", s: "Servaas (13 mei) moet de winter jagen, of we krijgen koude dagen." },
    { d: "22 mei", s: "Bonifatius (14 mei) koud en nat, brengt geen koren in het vat." },
    { d: "23 mei", s: "Sint-Sophia (15 mei) brengt de kou, zij zet de bloesem in de kou." },
    { d: "24 mei", s: "Meise mist, heeft de boer zich in de zomer vergist." },
    { d: "25 mei", s: "Als mei de bomen groen doet staan, zal de oogst heel voorspoedig gaan." },
    { d: "26 mei", s: "Mei helder en rein, zal een droog jaar zijn." },
    { d: "27 mei", s: "Een zachte mei brengt een rijke wei." },
    { d: "28 mei", s: "Regent het op Sint-Urbanusdag, men een goede wijnoogst verwachten mag." },
    { d: "29 mei", s: "Meise buien breken de kou, en zetten de boer uit de rouw." },
    { d: "30 mei", s: "Eindigt mei met warme dagen, zal de zomer ons behagen." },
    { d: "31 mei", s: "Mei koel and nat, geeft spek op het vat." },
        // --- JUNI (152 t/m 181) ---
    { d: "1 juni", s: "Juni vochtig en koel, maakt de boeren een heel goed gevoel." },
    { d: "2 juni", s: "Sint-Medardus (8 juni) nat, geeft veertig dagen nat op het pad." },
    { d: "3 juni", s: "Juni nat, de boer wordt zijn oogst zat." },
    { d: "4 juni", s: "Als het regent op Sint-Barnabas (11 juni), zwemt het koren in een plas." },
    { d: "5 juni", s: "Juni warm en droog, houdt de oogst de moed hoog." },
    { d: "6 juni", s: "Onweer in juni brengt een vruchtbaar jaar." },
    { d: "7 juni", s: "Sint-Jan (24 juni) nat, geeft een gevuld vat." },
    { d: "8 juni", s: "Als het regent op Sint-Jan, heeft men er dertig dagen van." },
    { d: "9 juni", s: "Vóór Sint-Jan mag men om regen bidden, daarna komt hij ongeroepen." },
    { d: "10 juni", s: "Sint-Pieter en Paulus (29 juni) helder en klaar, geeft een heel vruchtbaar jaar." },
    { d: "11 juni", s: "Juni koel en nat, vult de schuur maar niet het vat." },
    { d: "12 juni", s: "Als juni begint met zonneschijn, zal de zomer vol warmte zijn." },
    { d: "13 juni", s: "Juni droog, de boer houdt zijn hoofd omhoog." },
    { d: "14 juni", s: "Regen in juni is de boeren hun zegen." },
    { d: "15 juni", s: "Is juni warm en helder, vult de boer zijn kelder." },
    { d: "16 juni", s: "Juni stof op de wegen, brengt de natuur grote zegen." },
    { d: "17 juni", s: "Als de koekoek na Sint-Jan nog zingt, de zomer niet veel goeds meer brengt." },
    { d: "18 juni", s: "Juni wind uit het noorden, houdt de warmte uit alle oorden." },
    { d: "19 juni", s: "Onweer in juni vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "20 juni", s: "Juni regen, korenzegen." },
    { d: "21 juni", s: "Als juni nat is, klaagt de landman niet." },
    { d: "22 juni", s: "Sint-Medardus klaar en helder, vult het vat en ook de kelder." },
    { d: "23 juni", s: "Juni zacht, winter met macht." },
    { d: "24 juni", s: "Als het vriest op Sint-Barnabas, zwemt het koren in een plas." },
    { d: "25 juni", s: "Juni droog en heet, maakt de boer heel veel zweet." },
    { d: "26 juni", s: "Juni regen brengt geen zegen, als hij valt in de oogstmaand tegen." },
    { d: "27 juni", s: "Als juni begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "28 juni", s: "Juni koel, een mager gevoel." },
    { d: "29 juni", s: "Sint-Jan helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "30 juni", s: "Eindigt juni met warme dagen, zal de zomer ons behagen." },
    // --- JULI (182 t/m 212) ---
    { d: "1 juli", s: "Juli warm en droog, houdt de herfst de moed hoog." },
    { d: "2 juli", s: "Sint-Margaretha (20 juli) nat, geeft dertig dagen nat op het pad." },
    { d: "3 juli", s: "Valt er in juli veel nat, dan zwemt de boer op zijn eigen pad." },
    { d: "4 juli", s: "Sint-Jacob (25 juli) helder en warm, maakt de boer rijk en niet arm." },
    { d: "5 juli", s: "Als het regent op Sint-Jacob, is de oogst aan het koren schaars." },
    { d: "6 juli", s: "Juli helder en rein, zal een dry jaar zijn." },
    { d: "7 juli", s: "Onweer in juli brengt een vruchtbaar jaar." },
    { d: "8 juli", s: "Juli koel en nat, vult de schuur maar niet het vat." },
    { d: "9 juli", s: "Als juli begint met zonneschijn, zal de zomer vol warmte zijn." },
    { d: "10 juli", s: "Juli droog, de boer houdt zijn hoofd omhoog." },
    { d: "11 juli", s: "Regen in juli is de boeren hun zegen." },
    { d: "12 juli", s: "Is juli warm en helder, vult de boer zijn kelder." },
    { d: "13 juli", s: "Juli stof op de wegen, brengt de natuur grote zegen." },
    { d: "14 juli", s: "Onweer in juli vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "15 juli", s: "Juli regen, korenzegen." },
    { d: "16 juli", s: "Als juli nat is, klaagt de landman niet." },
    { d: "17 juli", s: "Juli zacht, winter met macht." },
    { d: "18 juli", s: "Juli droog Het groen des velds het oog bekoort, doch zelden houdt juli haar woord." },
    { d: "19 juli", s: "Juli koel, een mager gevoel." },
    { d: "20 juli", s: "Eindigt juli met warme dagen, zal de herfst ons behagen." },
    { d: "21 juli", s: "Sint-Margaretha klaar en helder, vult het vat en ook de kelder." },
    { d: "22 juli", s: "Juli nat, spek op het vat." },
    { d: "23 juli", s: "Als juli begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "24 juli", s: "Heeft juli veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "25 juli", s: "Juli warm, maakt de boer arm." },
    { d: "26 juli", s: "Als juli blaast op zijn hoorn, is het goed voor gras en koren." },
    { d: "27 juli", s: "Valt er sneeuw in juli, de winter nog niet wijken wil." },
    { d: "28 juli", s: "Valt juliwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "29 juli", s: "Een droge juli is niet de boeren hun wil." },
    { d: "30 juli", s: "Juli koud en nat, vult de schuur en ook het vat." },
    { d: "31 juli", s: "Juli koel en nat, geeft spek op het vat." },
        // --- AUGUSTUS (213 t/m 243) ---
    { d: "1 augustus", s: "Augustus warm en droog, houdt de herfst de moed hoog." },
    { d: "2 augustus", s: "Geeft begin augustus veel zonneschijn, dan zal het een strenge winter zijn." },
    { d: "3 augustus", s: "Als augustus zonder regen heen zou gaan, zou de boer in armoede staan." },
    { d: "4 augustus", s: "Onweer in augustus vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "5 augustus", s: "Sint-Laurens (10 aug) helder en warm, maakt de boer rijk en niet arm." },
    { d: "6 augustus", s: "Als het regent op Sint-Laurens, is de oogst aan het koren schaars." },
    { d: "7 augustus", s: "Augustus helder en rein, zal een droog jaar zijn." },
    { d: "8 augustus", s: "Onweer in augustus brengt een vruchtbaar jaar." },
    { d: "9 augustus", s: "Augustus koel en nat, vult de schuur maar niet het vat." },
    { d: "10 augustus", s: "Als augustus begins met zonneschijn, zal de herfst vol druiven zijn." },
    { d: "11 augustus", s: "Augustus droog, de boer houdt zijn hoofd omhoog." },
    { d: "12 augustus", s: "Regen in augustus is de boeren hun zegen." },
    { d: "13 augustus", s: "Is augustus warm en helder, vult de boer zijn kelder." },
    { d: "14 augustus", s: "Augustus stof op de wegen, brengt de natuur grote zegen." },
    { d: "15 augustus", s: "Augustus regen, korenzegen." },
    { d: "16 augustus", s: "Als augustus nat is, klaagt de landman niet." },
    { d: "17 augustus", s: "Augustus zacht, winter met macht." },
    { d: "18 augustus", s: "Augustus koel, een mager gevoel." },
    { d: "19 augustus", s: "Eindigt augustus met warme dagen, zal de winter ons behagen." },
    { d: "20 augustus", s: "Sint-Laurens klaar en helder, vult het vat en ook de kelder." },
    { d: "21 augustus", s: "Augustus nat, spek op het vat." },
    { d: "22 augustus", s: "Als augustus begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "23 augustus", s: "Heeft augustus veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "24 augustus", s: "Augustus warm, maakt de boer arm." },
    { d: "25 augustus", s: "Als augustus blaast op zijn hoorn, is het goed voor gras en koren." },
    { d: "26 augustus", s: "Valt juliwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "27 augustus", s: "Een droge augustus is niet de boeren hun wil." },
    { d: "28 augustus", s: "Augustus koud en nat, vult de schuur en ook het vat." },
    { d: "29 augustus", s: "Augustus koel en nat, geeft spek op het vat." },
    { d: "30 augustus", s: "Als de eerste week van augustus heet is, wordt de winter wit en lang." },
    { d: "31 augustus", s: "Augustusnoordenwind brengt standvastig weer." },
        // --- SEPTEMBER (244 t/m 273) ---
    { d: "1 september", s: "September warm en droog, houdt de herfst de moed hoog." },
    { d: "2 september", s: "Als het regent op Sint-Giel (1 sept), waait het nog veertig dagen." },
    { d: "3 september", s: "September helder en rein, zal een droog jaar zijn." },
    { d: "4 september", s: "Onweer in september brengt een vruchtbaar jaar." },
    { d: "5 september", s: "September koel en nat, vult de schuur maar niet het vat." },
    { d: "6 september", s: "Als september begint met zonneschijn, zal de herfst vol druiven zijn." },
    { d: "7 september", s: "September droog, de boer houdt zijn hoofd omhoog." },
    { d: "8 september", s: "Regen in september is de boeren hun zegen." },
    { d: "9 september", s: "Is september warm en helder, vult de boer zijn kelder." },
    { d: "10 september", s: "September stof op de wegen, brengt de natuur grote zegen." },
    { d: "11 september", s: "Onweer in september vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "12 september", s: "September regen, korenzegen." },
    { d: "13 september", s: "Als september nat is, klaagt de landman niet." },
    { d: "14 september", s: "September zacht, winter met macht." },
    { d: "15 september", s: "September koel, een mager gevoel." },
    { d: "16 september", s: "Eindigt september met warme dagen, zal de winter ons behagen." },
    { d: "17 september", s: "Sint-Giel klaar en helder, vult het vat en ook de kelder." },
    { d: "18 september", s: "September nat, spek op het vat." },
    { d: "19 september", s: "Als september begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "20 september", s: "Heeft september veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "21 september", s: "September warm, maakt de boer arm." },
    { d: "22 september", s: "Als september blaast op zijn hoorn, is het goed voor gras en koren." },
    { d: "23 september", s: "Valt septemberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "24 september", s: "Een droge september is niet de boeren hun wil." },
    { d: "25 september", s: "September koud en nat, vult de schuur en ook het vat." },
    { d: "26 september", s: "September koel en nat, geeft spek op het vat." },
    { d: "27 september", s: "Als septemberwind uit het zuiden waait, wordt het koren goed gezaaid." },
    { d: "28 september", s: "Septembermist brengt vaak vorst in de kist." },
    { d: "29 september", s: "Als de herfstmaand helder eindigt, de winter vroeg begint." },
    { d: "30 september", s: "Septemberregen op het zaad, is een zaak die de boer behaagt." },
        // --- OKTOBER (274 t/m 304) ---
    { d: "1 oktober", s: "Blinkt oktober in zonnegoud, de winter volgt dan snel en koud." },
    { d: "2 oktober", s: "Is oktober warm en fijn, het zal een scherpe winter zijn." },
    { d: "3 oktober", s: "Oktober veel gedruis, dan is het met de wijn niet pluis." },
    { d: "4 oktober", s: "Oktober warm en droog, houdt de winter de moed hoog." },
    { d: "5 oktober", s: "Sint-Gallus (16 okt) droog en fijn, geeft hoop op goede wijn." },
    { d: "6 oktober", s: "Als het regent op Sint-Gallus, zwemt het koren in een plas." },
    { d: "7 oktober", s: "Oktober helder en rein, zal een droog jaar zijn." },
    { d: "8 oktober", s: "Onweer in oktober brengt een vruchtbaar jaar." },
    { d: "9 oktober", s: "Oktober koel en nat, vult de schuur maar niet het vat." },
    { d: "10 oktober", s: "Als oktober begint met zonneschijn, zal de winter vol warmte zijn." },
    { d: "11 oktober", s: "Oktober droog, de boer houdt zijn hoofd omhoog." },
    { d: "12 oktober", s: "Regen in oktober is de boeren hun zegen." },
    { d: "13 oktober", s: "Is oktober warm en helder, vult de boer zijn kelder." },
    { d: "14 oktober", s: "Oktober stof op de wegen, brengt de natuur grote zegen." },
    { d: "15 oktober", s: "Onweer in oktober vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "16 oktober", s: "Oktober regen, korenzegen." },
    { d: "17 oktober", s: "Als oktober nat is, klaagt de landman niet." },
    { d: "18 oktober", s: "Oktober zacht, winter met macht." },
    { d: "19 oktober", s: "Oktober koel, een mager gevoel." },
    { d: "20 oktober", s: "Eindigt oktober met warme dagen, zal de winter ons behagen." },
    { d: "21 oktober", s: "Sint-Gallus klaar en helder, vult het vat en ook de kelder." },
    { d: "22 oktober", s: "Oktober nat, spek op het vat." },
    { d: "23 oktober", s: "Als oktober begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "24 oktober", s: "Heeft oktober veel zonneschijn, the wijn zal des te beter zijn." },
    { d: "25 oktober", s: "Oktober warm, maakt de boer arm." },
    { d: "26 oktober", s: "Als oktober blaast op zijn hoorn, is het goed voor gras i koren." },
    { d: "27 oktober", s: "Valt oktoberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "28 oktober", s: "Een droge oktober is niet de boeren hun wil." },
    { d: "29 oktober", s: "Oktober koud en nat, vult de schuur en ook het vat." },
    { d: "30 oktober", s: "Oktober koel en nat, geeft spek op het vat." },
    { d: "31 oktober", s: "Als in oktober de bladeren snel vallen, zal de winter hard knallen." },
        // --- NOVEMBER (305 t/m 334) ---
    { d: "1 november", s: "Sint-Maarten (11 nov) helder en warm, maakt de boer rijk en niet arm." },
    { d: "2 november", s: "Als het regent op Sint-Maarten, is de winter in de kaarten." },
    { d: "3 november", s: "November warm en droog, houdt de winter de moed hoog." },
    { d: "4 november", s: "Sint-Andries (30 nov) helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "5 november", s: "Als het waait op Sint-Andries, waait het nog veertig dagen." },
    { d: "6 november", s: "November helder en rein, zal een droog jaar zijn." },
    { d: "7 november", s: "Onweer in november brengt een vruchtbaar jaar." },
    { d: "8 november", s: "November koel en nat, vult de schuur maar niet het vat." },
    { d: "9 november", s: "Als november begint met zonneschijn, zal de winter vol warmte zijn." },
    { d: "10 november", s: "November droog, de boer houdt zijn hoofd omhoog." },
    { d: "11 november", s: "Regen in november is de boeren hun zegen." },
    { d: "12 november", s: "Is november warm en helder, vult de boer zijn kelder." },
    { d: "13 november", s: "November stof op de wegen, brengt de natuur grote zegen." },
    { d: "14 november", s: "Onweer in november vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "15 november", s: "November regen, korenzegen." },
    { d: "16 november", s: "Als november nat is, klaagt de landman niet." },
    { d: "17 november", s: "November zacht, winter met macht." },
    { d: "18 november", s: "November koel, een mager gevoel." },
    { d: "19 november", s: "Eindigt november met warme dagen, zal de winter ons behagen." },
    { d: "20 november", s: "Sint-Maarten klaar en helder, vult het vat en ook de kelder." },
    { d: "21 november", s: "November nat, spek op het vat." },
    { d: "22 november", s: "Als november begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "23 november", s: "Heeft november veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "24 november", s: "November warm, maakt de boer arm." },
    { d: "25 november", s: "Als november blaast op zijn hoorn, is het goed voor gras en koren." },
    { d: "26 november", s: "Valt novemberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "27 november", s: "Een droge november is niet de boeren hun wil." },
    { d: "28 november", s: "November koud en nat, vult de schuur en ook het vat." },
    { d: "29 november", s: "November koel en nat, geeft spek op het vat." },
    { d: "30 november", s: "Zwaait november met zijn staart, de winter is een vroege gast." },
        // --- DECEMBER (335 t/m 365) ---
    { d: "1 december", s: "De dagen lengen de nachten strengen na een koude decembernacht." },
    { d: "2 december", s: "December warm en droog, houdt de lente de moed hoog." },
    { d: "3 december", s: "Sint-Thomas (21 dec) helder en fijn, belooft een goed jaar voor de wijn." },
    { d: "4 december", s: "Als het waait op Sint-Thomas, waait het nog veertig dagen." },
    { d: "5 december", s: "December helder en rein, zal een droog jaar zijn." },
    { d: "6 december", s: "Onweer in december brengt een vruchtbaar jaar." },
    { d: "7 december", s: "December koel en nat, vult de schuur maar niet het vat." },
    { d: "8 december", s: "Als december begint met zonneschijn, zal de winter vol warmte zijn." },
    { d: "9 december", s: "December droog, de boer houdt zijn hoofd omhoog." },
    { d: "10 december", s: "Regen in december is de boeren hun zegen." },
    { d: "11 december", s: "Is december warm en helder, vult de boer zijn kelder." },
    { d: "12 december", s: "December stof op de wegen, brengt de natuur grote zegen." },
    { d: "13 december", s: "Onweer in december vroeg in de morgen, brengt de boer grote zorgen." },
    { d: "14 december", s: "December regen, korenzegen." },
    { d: "15 december", s: "Als december nat is, klaagt de landman niet." },
    { d: "16 december", s: "December zacht, winter met macht." },
    { d: "17 december", s: "December koel, een mager gevoel." },
    { d: "18 december", s: "Eindigt december met warme dagen, zal de winter ons behagen." },
    { d: "19 december", s: "Sint-Thomas klaar en helder, vult het vat en ook de kelder." },
    { d: "20 december", s: "December nat, spek op het vat." },
    { d: "21 december", s: "Als december begint met wind en regen, is dat voor de vruchten geen zegen." },
    { d: "22 december", s: "Heeft december veel zonneschijn, de wijn zal des te beter zijn." },
    { d: "23 december", s: "December warm, maakt de boer arm." },
    { d: "24 december", s: "Als december blaast op zijn hoorn, is het goed voor gras en koren." },
    { d: "25 december", s: "Valt decemberwind uit het noorden, de kou houdt aan op alle oorden." },
    { d: "26 december", s: "Een droge december is niet de boeren hun wil." },
    { d: "27 december", s: "December koud en nat, vult de schuur en ook het vat." },
    { d: "28 december", s: "December koel en nat, geeft spek op het vat." },
    { d: "29 december", s: "Een witte kerst brengt een groene Pasen." },
    { d: "30 december", s: "Als december eindigt met felle kou, bouwt men op een goede oogst." },
    { d: "31 december", s: "Zijn de nachten in december kort en grijs, men gaat dan niet gerust op reis." },
    { d: "29 februari", s: "Als februari achtentwintig dagen telt, blijft de schrikkelspreuk buiten het veld. Maar komt de negenentwintigste aan bod, dan schrikkelen het weer en de natuur op slot." }
];

